# Generated by Django 4.0.3 on 2022-03-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
        ('ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='id_pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.pharmacie'),
        ),
    ]
