# Generated by Django 4.0.3 on 2022-03-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0002_alter_ordonnance_id_pharmacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='id_medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordonnance.medicament'),
        ),
    ]
