# Generated by Django 4.0.3 on 2022-04-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
        ('patient', '0002_alter_patient_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('ville', models.CharField(max_length=250)),
                ('INP', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.person')),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('medcin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
