# Generated by Django 4.0.3 on 2022-03-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('activated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ville', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=255)),
                ('medcin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
