# Generated by Django 4.0.3 on 2022-03-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visite',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='visite',
            name='ville',
        ),
        migrations.AlterField(
            model_name='visite',
            name='medcin_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
