# Generated by Django 4.0.3 on 2022-04-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('mutuelle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_mutuelle',
            new_name='AllMutuelle',
        ),
    ]
