# Generated by Django 4.0.3 on 2022-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=255)),
                ('activated', models.BooleanField()),
            ],
        ),
    ]
