# Generated by Django 4.0.3 on 2022-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutuelle', '0003_allmutuelle_visite_id_alter_allmutuelle_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmutuelle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
