# Generated by Django 4.0.3 on 2022-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('datedenaissance', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('ville', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('permission_privacy', models.BooleanField(default=0)),
                ('a_mutuelle', models.BooleanField()),
                ('immatriculation', models.IntegerField()),
                ('activated', models.BooleanField(default=0)),
            ],
        ),
    ]
